# /docker-compose.yml
version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    links:
      - database

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  database:
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports:
      - "5432:5432"
